### ISSUE TITLE
Collapsible areas with the same ID

### ISSUE THREAD

**Issue by nmouillet** [eberhardt/moodle-filter_collapsible#1]
I notice than collapsible areas could have the same ID if there are areas in two differents section's description. In this case, the first collapsible area have two arrows on it's right while the second have no arrow at all. Both doesn't work anymore (ref attached picture).

![collapsible](https://cloud.githubusercontent.com/assets/6358307/10186140/12ca1638-674f-11e5-97cd-156f3b631331.PNG)

I suggest to use PHP session in replace_collapsible() to store the collapsible area ID or more simply to set $id as a global variable.

$collapsible_region_id = 0;
class filter_collapsible extends moodle_text_filter {
[...]
private function replace_collapsible(&$text) {
global $collapsible_region_id;
[...]
$replaced .= $this->start_region('collapsible' . $collapsible_region_id++, $more, $split);
[...]
}
}

**Comment by eberhardt** [comment]
The `static` statement should have carried that issue away. Do you have fetched the latest code?

**Comment by nmouillet** [comment]
I think so, here is my version.php:
$plugin->version   = 2015010800;
$plugin->requires  = 2014050800;
$plugin->component = 'filter_collapsible';
$plugin->release   = '1.0';
$plugin->maturity   = MATURITY_RC;

EDIT:
In fact no, the code is different but it's the same version.php. I've downloaded your plugin in the Moodle plugin directory last week... is it updated?

**Comment by eberhardt** [comment]
I think, I didn't modified the `version.php` (which was a little bit stupid) for the fix. If you're using git, your _HEAD_ must be at e627d3c

**Comment by eberhardt** [comment]
Or just look at the `/filter.php` and check, if there is the `static` statement in the first row after the functions name.

**Comment by nmouillet** [comment]
I've checked the code available here : https://moodle.org/plugins/pluginversions.php?plugin=filter_collapsible and it doesn't contain the static statement and release date is january 12. This filter is great, I think it could be a good idea to update it into the moodle plugin directory. Anyway I'll "Git" it ;)

**Comment by eberhardt** [comment]
Yeah... I now see the problem. I didn't updated the zip download. Maybe I should. :/

Thx for reporting.
